apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  dnsNames:
    - welcome.tani-exe.f5.si
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned