apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: default
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.8
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: "ruuto"
        volumeMounts:
        - name: database1
          mountPath: /var/lib/mysql/
  volumeClaimTemplates:
  - metadata:
      name: database1
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi