apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv02
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  iscsi:
    targetPortal: 192.168.3.240:3260
    iqn: iqn.2005-10.org.freenas.ctl:target01
    lun: 2
    readOnly: false
