apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.214
  ports:
  - name: "mysql-port"
    protocol: "TCP"
    port: 3306
  selector:
    app: mariadb