apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: default
spec:
  serviceName: gitea
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: mariadb
    spec:gitea
      containers:
      - name: gitea
        image: gitea/gitea:1.19
        ports:
        - containerPort: 3000
          name: gitea
        volumeMounts:
        - mountPath: /data
          name: git-data
  volumeClaimTemplates:
  - metadata:
      name: git-data
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi