apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-gitea
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  iscsi:
    targetPortal: 192.168.3.241:3260
    iqn: iqn.2000-01.com.synology:tani-nas.Target-1.3c2cf4b6fd1
    lun: 1
    readOnly: false
