apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-media-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - vers=3.0
  csi:
    driver: csi/cifs
    volumeHandle: cifs-volume
    readOnly: false
    volumeAttributes:
      server: 192.168.3.240
      share: /media/media
      username:               
        valueFrom:
          secretKeyRef:
            name: truenas-smb
            key: user
      password:
        valueFrom:
          secretKeyRef:
            name: truenas-smb
            key: pass

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - vers=3.0
  csi:
    driver: csi/cifs
    volumeHandle: cifs-volume
    readOnly: false
    volumeAttributes:
      server: 192.168.3.240
      share: /media/config
      username:               
        valueFrom:
          secretKeyRef:
            name: truenas-smb
            key: user
      password:
        valueFrom:
          secretKeyRef:
            name: truenas-smb
            key: pass

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - vers=3.0
  csi:
    driver: csi/cifs
    volumeHandle: cifs-volume
    readOnly: false
    volumeAttributes:
      server: 192.168.3.240
      share: /media/cache
      username:               
        valueFrom:
          secretKeyRef:
            name: truenas-smb
            key: user
      password:
        valueFrom:
          secretKeyRef:
            name: truenas-smb
            key: pass
