apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.3.240
    path: /mnt/main/kubernetes-jellyfin
