apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-media-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  nfs:
    server: 192.168.3.240
    path: /mnt/main/kubernetes-jellyfin/media

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  nfs:
    server: 192.168.3.240
    path: /mnt/main/kubernetes-jellyfin/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  nfs:
    server: 192.168.3.240
    path: /mnt/main/kubernetes-jellyfin/cache
