apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
spec:
  serviceName: nextcloud
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud
          resources:
            requests:  # ここで指定
              cpu: 0.5
              memory: 1Gi
            limits: # ここで制限を指定
              cpu: 10.7
              memory: 1.5Gi
        volumeMounts:
        - name: nextcloud
          mountPath: /var/www/html/
        env:
          - name: OVERWRITEPROTOCOL
            value: "https"
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: "cloud.tani-exe.f5.si"
  volumeClaimTemplates:
  - metadata:
      name: nextcloud
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi