apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv01
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  iscsi:
    targetPortal: 192.168.3.240:3261
    iqn: iqn.2005-10.org.freenas.ctl:target01
    lun: 1
    readOnly: false
