---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-bd
  labels:
    role: service-config
    app: spring-bd
data:
  # Find more options at https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
  # Remove # from in front of line if changing from default values.
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  #GAMEMODE: "survival" # Options: survival, creative, adventure
  DIFFICULTY: "normal" # Options: peaceful, easy, normal, hard
  #DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
  #LEVEL_NAME: "my_minecraft_world"
  LEVEL_SEED: "4364519598890647509"
  SERVER_NAME: "谷鯖春"
  #SERVER_PORT: "19132"
  #LEVEL_TYPE: "DEFAULT" # Options: FLAT, LEGACY, DEFAULT
  #ALLOW_CHEATS: "false" # Options: true, false
  MAX_PLAYERS: "20"
  #PLAYER_IDLE_TIMEOUT: "30"
  #TEXTUREPACK_REQUIRED: "false" # Options: true, false
  #
  ## Changing these will have a security impact
  #ONLINE_MODE: "true" # Options: true, false (removes Xbox Live account requirements)
  #WHITE_LIST: "false" # If enabled, need to provide a whitelist.json by your own means. 
  #
  ## Changing these will have a performance impact
  #VIEW_DISTANCE: "10"
  #TICK_DISTANCE: "4"
  #MAX_THREADS: "8"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: spring-bd
  name: spring-bd
spec:
  replicas: 1
  serviceName: spring-bd
  selector:
    matchLabels:
      app: spring-bd
  template:
    metadata:
      labels:
        app: spring-bd
    spec:
      containers:
        - name: main
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          resources:
            requests:  # ここで指定
              cpu: 1
              memory: 1.5Gi
            limits: # ここで制限を指定
              cpu: 2
              memory: 1.5Gi
          envFrom:
            - configMapRef:
                name: spring-bd
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 19132
              protocol: UDP
          readinessProbe: &probe
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                - 127.0.0.1
            initialDelaySeconds: 30
          livenessProbe: *probe
          tty: true
          stdin: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: synostorage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-bd
spec:
  selector:
    app: spring-bd
  loadBalancerIP: 192.168.3.219
  ports:
    - port: 19132
      protocol: UDP
  ipFamily: IPv4
  type: LoadBalancer