apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-minecraft-01
  namespace: default
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  iscsi:
    targetPortal: 192.168.3.240:3261
    iqn: iqn.2005-10.org.freenas.ctl:target01
    lun: 6
    readOnly: false
