apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - welcome.tani-exe.f5.si
  secretName: example-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard
  namespace: kubernetes-dashboard
spec:
  dnsNames:
    - dashboard.tani-exe.f5.si
  secretName: dashboard-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer