apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - welcome.tani-exe.f5.si
  secretName: example-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard
  namespace: kubernetes-dashboard
spec:
  dnsNames:
    - dashboard.tani-exe.f5.si
  secretName: dashboard-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  dnsNames:
    - argocd.tani-exe.f5.si
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud
  namespace: default
spec:
  dnsNames:
    - cloud.tani-exe.f5.si
  secretName: cloud-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: result-api
  namespace: default
spec:
  dnsNames:
    - api.result-database.tani-exe.f5.si
  secretName: result-api-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo4513-minio-console
  namespace: default
spec:
  dnsNames:
    - console.s3.4513echo.tani-exe.f5.si
  secretName: echo4513-minio-console-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo4513-minio
  namespace: default
spec:
  dnsNames:
    - s3.4513echo.tani-exe.f5.si
  secretName: echo4513-minio-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer