apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress03
  namespace: argocd
spec:
  rules:
    - host: argocd.tani-exe.f5.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80