apiVersion: apps/v1
kind: Pod
metadata:
  name: nginx01
  namespace: default
spec:
  containers:
  - name: nginx01
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx01
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: nginx01