apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: echo4513-postgresql
spec:
  selector:
    matchLabels:
      app: echo4513-postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: echo4513-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        resources:
          requests:  # ここで指定
            cpu: 1
            memory: 1.5Gi
          limits: # ここで制限を指定
            cpu: 1.5
            memory: 2Gi
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: echo4513-postgres
                key: pass
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: echo4513-postgres
                key: user
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi