apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: echo4513-postgresql
spec:
  selector:
    matchLabels:
      app: echo4513-postgres
  serviceName: "postgres"
  replicas: 0
  template:
    metadata:
      labels:
        app: echo4513-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        resources:
          requests:  # ここで指定
            cpu: 1
            memory: 1.5Gi
          limits: # ここで制限を指定
            cpu: 1.5
            memory: 2Gi
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: echo4513-postgres
                key: pass
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: echo4513-postgres
                key: user
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      storageClassName: nfs-csi
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi