apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-minio
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  iscsi:
    targetPortal: 192.168.3.240:3261
    iqn: iqn.2005-10.org.freenas.ctl:echo4513
    lun: 0
    readOnly: false
