apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx01
  namespace: default
spec:
  secretName: nginx01-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: tani-exe.f5.si
  dnsNames:
  - tani-exe.f5.si