# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: nfs-csi
# provisioner: nfs.csi.k8s.io
# parameters:
#   server: 192.168.3.192
#   share: /export/nfs
# reclaimPolicy: Retain 
# volumeBindingMode: Immediate
# mountOptions:
#   - nfsvers=4.1

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-block
provisioner: driver.longhorn.io
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480" # 8 hours in minutes
