apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry
spec:
  serviceName: docker-registry
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:2.7
        env:
          - name: REGISTRY_HTTP_ADDR
            value: ":5000"
          - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
            value: "/var/lib/registry"
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: image-store
    spec:
      accessModes: 
      - ReadWriteOnce
      storageClassName: "nfs-csi"
      resources:
        requests:
          storage: 5Gi